<!-- general theme begins / Début du thème général -->
		<div class="cn-toppage"><a href="#cn-tphp" title="Return to Top of Page">Top of Page</a></div>
		<section>
			<h2>Heading level&#160;2 (h2)</h2>

			<div class="cn-toppage"><a href="#cn-tphp" title="Return to Top of Page">Top of Page</a></div>
			<section>
				<h3>Heading level&#160;3 (h3)</h3>

				<div class="cn-toppage"><a href="#cn-tphp" title="Return to Top of Page">Top of Page</a></div>
				<section>
					<h4>Heading level&#160;4 (h4)</h4>

					<div class="cn-toppage"><a href="#cn-tphp" title="Return to Top of Page">Top of Page</a></div>
					<section>
						<h5>Heading level&#160;5 (h5)</h5>

						<div class="cn-toppage"><a href="#cn-tphp" title="Return to Top of Page">Top of Page</a></div>
						<section>
							<h6>Heading level&#160;6 (h6)</h6>

							<p>CONTENT (a mix of text and images or graphics is expected)</p>			
						</section>
					</section>
				</section>
			</section>
		</section>
	</section>
	<hr />
	<section>
		<dl id="cn-doc-dates" role="contentinfo">
			<dt>Date Modified:</dt>
			<dd><span><time>2010-08-09</time></span></dd>
		</dl>
<!-- general theme ends / Fin du thème général -->
