<!-- general theme begins / Début du thème général -->
		<!-- Common menu bar begins / Début de la barre de menu commune --> 	
		<div id="cn-cmb">
			<h3>Barre de menu commune</h3>
			<nav role="navigation">		
				<ul>
					<li id="cn-cmb1"><a href="#" title="Contactez-nous - Coordonnées importantes">Contactez-nous</a></li>
					<li id="cn-cmb2"><a href="#" title="Aide - Renseignements sur la façon d'utiliser le site Web">Aide</a></li>
					<li id="cn-cmb3"><a href="#" title="Plan de site - Plan de site du site Web">Plan de site</a></li>
					<li id="cn-cmb4"><a rel="external" href="http://www.canada.gc.ca/accueil.html" title="canada.gc.ca - Site Web du gouvernement du Canada">canada.gc.ca</a></li>
				</ul>
			</nav>
		</div>
		<!-- Common menu bar ends / Fin de la barre de menu commune --> 

		<div id="cn-in-pd">			
			<h3>Avis importants</h3>
			<div id="cn-sig"><img src="theme-general/images/sig-fra.gif" width="372" height="20" alt="Gouvernement du Canada" title="Gouvernement du Canada" /></div>
			<div id="cn-toppage-foot"><a href="#cn-tphp" title="Retourner au haut de la page">Haut de la page</a></div>
			<div id="cn-in-pd-links">
				<ul>
					<li id="cn-inotices-link"><a href="#" rel="license">Avis importants</a></li>
				</ul>
			</div>
		</div>
<!-- general theme ends / Fin du thème général -->
