<!-- general theme begins / Début du thème général -->
		<ul id="cn-lang-links">
			<li><a href="theme-general/3col-theme-clf2-nsi2-eng.html" lang="en" title="English - English version of the Web page">English</a></li>
		</ul>
		<div id="cn-wmms"><img src="theme-general/images/wmms.gif" width="83" height="20" alt="Symbole du gouvernement du Canada" title="Symbole du gouvernement du Canada" /></div>

		<!-- Banner begins / Début de la bannière -->
		<div id="cn-banner" role="banner">
			<p id="cn-banner-text">Texte de la bannière</p>
		</div>
		<!-- Banner ends / Fin de la bannière -->

		<!-- Breadcrumb begins / Début du fil d'Ariane -->
		<div id="cn-bcrumb">
		<nav role="navigation">
			<h2>Fil d'Ariane</h2>
			<ol>
				<li><a rel="up up up" href="#" title="Accueil - Page principale du site Web">Accueil</a>&#160;&#62;</li>
				<li><a rel="up up" href="#">Niveau&#160;1</a>&#160;&#62;</li>
				<li><a rel="up" href="#">Niveau&#160;2</a>&#160;&#62;</li>
				<li>Thème général - HTML5 - Boîte à outils de l'expérience Web (BOEW)</li>
			</ol>
		</nav>
		</div>
		<!-- Breadcrumb ends / Fin du fil d'Ariane -->
<!-- general theme ends / Fin du thème général -->
