<!-- general theme begins / Début du thème général -->
			<section>
				<h3>Section&#160;1</h3>
				<ul>
					<li><a href="#">Item&#160;1a</a>
					<ul>
						<li><a href="#">Item&#160;1b</a></li>
						<li><a href="#">Item&#160;2b</a></li>
					</ul>
					</li>
					<li><a href="#">Item&#160;2a</a></li>
					<li><a href="#">Item&#160;3a</a></li>
				</ul>		
			</section>
			<section>
				<h3>Section&#160;2</h3>
				<ul>
					<li><a href="#">Item&#160;1a</a></li>
					<li><a href="#">Item&#160;2a</a></li>
					<li><a href="#">Item&#160;3a</a></li>
				</ul>
			</section>
<!-- general theme ends / Fin du thème général -->
