<!-- general theme begins / Début du thème général -->
		<div class="cn-toppage"><a href="#cn-tphp" title="Retourner au haut de la page">Haut de la page</a></div>
			<h2>L'en-tête de niveau&#160;2 (h2)</h2>

			<div class="cn-toppage"><a href="#cn-tphp" title="Retourner au haut de la page">Haut de la page</a></div>
				<h3>L'en-tête de niveau&#160;3 (h3)</h3>

				<div class="cn-toppage"><a href="#cn-tphp" title="Retourner au haut de la page">Haut de la page</a></div>
					<h4>L'en-tête de niveau&#160;4 (h4)</h4>

					<div class="cn-toppage"><a href="#cn-tphp" title="Retourner au haut de la page">Haut de la page</a></div>
						<h5>L'en-tête de niveau&#160;5 (h5)</h5>

						<div class="cn-toppage"><a href="#cn-tphp" title="Retourner au haut de la page">Haut de la page</a></div>
							<h6>L'en-tête de niveau&#160;6 (h6)</h6>

							<p>CONTENU (un mélange de texte et d'images ou de graphiques est prévu)</p>
	<hr />
		<dl id="cn-doc-dates">
			<dt>Date de modification&#160;:</dt>
			<dd><span>2010-08-09</span></dd>
		</dl>
<!-- general theme ends / Fin du thème général -->
