<!-- general theme begins / Début du thème général -->
		<div class="cn-toppage"><a href="#cn-tphp" title="Return to Top of Page">Top of Page</a></div>
			<h2>Heading level&#160;2 (h2)</h2>

			<div class="cn-toppage"><a href="#cn-tphp" title="Return to Top of Page">Top of Page</a></div>
				<h3>Heading level&#160;3 (h3)</h3>

				<div class="cn-toppage"><a href="#cn-tphp" title="Return to Top of Page">Top of Page</a></div>
					<h4>Heading level&#160;4 (h4)</h4>

					<div class="cn-toppage"><a href="#cn-tphp" title="Return to Top of Page">Top of Page</a></div>
						<h5>Heading level&#160;5 (h5)</h5>

						<div class="cn-toppage"><a href="#cn-tphp" title="Return to Top of Page">Top of Page</a></div>
							<h6>Heading level&#160;6 (h6)</h6>

							<p>CONTENT (a mix of text and images or graphics is expected)</p>			
	<hr />
		<dl id="cn-doc-dates">
			<dt>Date Modified:</dt>
			<dd><span>2010-08-09</span></dd>
		</dl>
<!-- general theme ends / Fin du thème général -->
