<!-- general theme begins / Début du thème général -->
	<link href="theme-general/css/theme-general.css" rel="stylesheet" type="text/css" />
	<!--[if IE 7]><link href="theme-general/css/theme-general-ie7.css" rel="stylesheet" type="text/css" /><![endif]-->
	<!--[if lte IE 6]><link href="theme-general/css/theme-general-ie6.css" rel="stylesheet" type="text/css" /><![endif]-->
<!-- general theme ends / Fin du thème général -->
