<!-- general theme begins / Début du thème général -->
		<!-- Common menu bar begins / Début de la barre de menu commune --> 	
		<div id="cn-cmb" >
			<h3>Common menu bar</h3>
				<ul>
					<li id="cn-cmb1"><a href="#" title="Contact Us - Important contact information">Contact Us</a></li>
					<li id="cn-cmb2"><a href="#" title="Help - Information about using the Web site">Help</a></li>
					<li id="cn-cmb3"><a href="#" title="Site Map - Site Map for the Web site">Site Map</a></li>
					<li id="cn-cmb4"><a rel="external" href="http://www.canada.gc.ca/home.html" title="canada.gc.ca - Government of Canada Web site">canada.gc.ca</a></li>
				</ul>
		</div>
		<!-- Common menu bar ends / Fin de la barre de menu commune --> 

		<div id="cn-in-pd">			
			<h3>Important Notices</h3>
			<div id="cn-sig"><img src="theme-general/images/sig-eng.gif" width="372" height="20" alt="Government of Canada" title="Government of Canada" /></div>
			<div id="cn-toppage-foot"><a href="#cn-tphp" title="Return to Top of Page">Top of Page</a></div>
			<div id="cn-in-pd-links">
				<ul>
					<li id="cn-inotices-link"><a href="#" rel="license">Important Notices</a></li>
				</ul>
			</div>
		</div>
<!-- general theme ends / Fin du thème général -->
