<!-- general theme begins / Début du thème général -->
		<ul id="cn-lang-links">
			<li><a href="theme-general/xhtml/3col-theme-general-xhtml-fra.html" lang="fr" xml:lang="fr" title="Français - Version française de cette page">Français</a></li>
		</ul>
		<div id="cn-wmms"><img src="theme-general/images/wmms.gif" width="83" height="20" alt="Symbol of the Government of Canada" title="Symbol of the Government of Canada" /></div>

		<!-- Banner begins / Début de la bannière -->
		<div id="cn-banner">
			<p id="cn-banner-text">Banner Text</p>
		</div>
		<!-- Banner ends / Fin de la bannière -->

		<!-- Breadcrumb begins / Début du fil d'Ariane -->
		<div id="cn-bcrumb">
			<h2>Breadcrumb</h2>
			<ol>
				<li><a rel="up up up" href="#" title="Home - Main page of the Web site">Home</a>&#160;&#62;</li>
				<li><a rel="up up" href="#">Level&#160;1</a>&#160;&#62;</li>
				<li><a rel="up" href="#">Level&#160;2</a>&#160;&#62;</li>
				<li>General Theme - Web Experience Toolkit (WET)</li>
			</ol>
		</div>
		<!-- Breadcrumb ends / Fin du fil d'Ariane -->
<!-- general theme ends / Fin du thème général -->
