<!-- base theme begins / Début du thème base -->
		<p>Normally contains the main content of the page and the date the content was last modified.</p>

		<section>
			<h2>Important default values</h2>
			<p><strong>Note:</strong> Default values are for the base CSS and not the current theme.</p>
			<dl>
				<dt><code>cn-centre-col-inner</code>:</dt>
				<dd>
					<ul>
						<li><code>margin-left: 25%</code> (must equal the <code>cn-left-col</code> width)</li>
						<li><code>padding: 1px 5px;</code></li>
						<li><code>background: #FFF</code></li>
					</ul>
				</dd>
				<dt><code>cn-centre-col-gap</code> (gap between the column and the footer):</dt>
				<dd>
					<ul>
						<li><code>margin-left: 25%</code> (must equal the <code>cn-left-col</code> width)</li>
						<li><code>background: #FFF</code></li>
					</ul>
				</dd>
			</dl>
		</section>
<!-- base theme ends / Fin du thème base -->
