<!-- base theme begins / Début du thème base -->
		<p>Contient normalement le contenu principal de la page et la date de la dernière modification.</p>

		<section>
			<h2>Valeurs implicites importantes</h2>
			<p><strong>Nota&#160;:</strong> Les valeurs implicites sont pour le CSS base et pas pour le thème actuel.</p>
			<dl lang="en" xml:lang="en">
				<dt><code>cn-centre-col-inner</code>&#160;:</dt>
				<dd>
					<ul>
						<li><code>margin-right: 0</code></li>
						<li><code>margin-left: 25%</code> (must equal the <code>cn-left-col</code> width)</li>
						<li><code>padding: 1px 5px;</code></li>
						<li><code>background: #FFF</code></li>
					</ul>
				</dd>
				<dt><code>cn-centre-col-gap</code> (l'écart entre la colonne et le pied de page)&#160;:</dt>
				<dd>
					<ul>
						<li><code>margin-left: 25%</code> (must equal the <code>cn-left-col</code> width)</li>
						<li><code>background: #FFF</code></li>
					</ul>
				</dd>
			</dl>
		</section>
<!-- base theme ends / Fin du thème base -->
