<!-- base theme begins / Début du thème base -->
		<h2>En-tête (base)</h2>

		<h3>Valeurs implicites importantes</h3>
		<p><strong>Nota&#160;:</strong> Les valeurs implicites sont pour le CSS base et pas pour le thème actuel.</p>
		<dl lang="en" xml:lang="en">
			<dt><code>cn-head</code>&#160;:</dt>
			<dd>
				<ul>
					<li><code>background: #FFF</code></li>
				</ul>
			</dd>
		</dl>
<!-- base theme ends / Fin du thème base -->
