<!-- base theme begins / Début du thème base -->
			<section>
				<h3>Primary navigation (Base)</h3>
				<p>Normally contains a search field and navigation links</p>

				<section>		
					<h4>Important default values</h4>
					<p><strong>Note:</strong> Default values are for the base CSS and not the current theme.</p>
					<dl>
					<dt><code>cn-left-col</code>:</dt>
					<dd>
						<ul>
							<li><code>width: 25%</code></li>
							<li><code>margin-right: -25%</code> (must equal the negative of the <code>cn-left-col</code> width)</li>
						</ul>
					</dd>
					<dt><code>cn-left-col-inner</code>:</dt>
					<dd>
						<ul>
							<li><code>background: #FFF</code></li>
						</ul>
					</dd>
					<dt><code>cn-left-col-gap</code> (gap between the column and the footer):</dt>
					<dd> 
						<ul>
							<li><code>width: 25%</code> (must equal the <code>cn-left-col</code> width)</li>
							<li><code>background: #FFF</code></li>
						</ul>
					</dd>
					</dl>
				</section>
			</section>
<!-- base theme ends / Fin du thème base -->
