<!-- base theme begins / Début du thème base -->
			<section>
				<h3>Navigation principale (base)</h3>
				<p>Contient normalement un champ de recherche et les liens de navigation</p>

				<section>		
					<h4>Valeurs implicites importantes</h4>
					<p><strong>Nota&#160;:</strong> Les valeurs implicites sont pour le CSS base et pas pour le thème actuel.</p>
					<dl lang="en" xml:lang="en">
					<dt><code>cn-left-col</code>&#160;:</dt>
					<dd>
						<ul>
							<li><code>width: 25%</code></li>
							<li><code>margin-right: -25%</code> (<span lang="fr" xml:lang="fr">doit égaler le négatif de la largeur</span> <code>cn-left-col</code>)</li>
						</ul>
					</dd>
					<dt><code>cn-left-col-inner</code>&#160;:</dt>
					<dd>
						<ul>
							<li><code>background: #FFF</code></li>
						</ul>
					</dd>
					<dt><code>cn-left-col-gap</code> (l'écart entre la colonne et le pied de page)&#160;:</dt>
					<dd> 
						<ul>
							<li><code>width: 25%</code> (<span lang="fr" xml:lang="fr">doit égaler la largeur</span> <code>cn-left-col</code>)</li>
							<li><code>background: #FFF</code></li>
						</ul>
					</dd>
					</dl>
				</section>
			</section>
<!-- base theme ends / Fin du thème base -->
