<!-- base theme begins / Début du thème base -->
		<section>
			<h3>Supplemental content (Base)</h3>
			<p>Normally contains featured content and links</p>
	
			<section>		
				<h4>Important default values</h4>
				<p><strong>Note:</strong> Default values are for the base CSS and not the current theme.</p>
				<dl>
				<dt><code>cn-right-col</code>:</dt>
				<dd>
					<ul>
						<li><code>width: 25%</code></li>
					</ul>
				</dd>
				<dt><code>cn-right-col-inner</code>:</dt>
				<dd>
					<ul>
						<li><code>background: #FFF</code></li>
					</ul>
				</dd>
				<dt><code>cn-right-col-gap</code> (gap between the column and the footer):</dt>
				<dd>
					<ul>
						<li><code>width: 25%</code> (must equal the <code>cn-right-col</code> width)</li>
						<li><code>background: #FFF</code></li>
					</ul>
				</dd>
				</dl>
			</section>
		</section>
<!-- base theme ends / Fin du thème base -->
